spring:
  config:
    activate:
      on-profile: create

  datasource:
    url: jdbc:h2:tcp://localhost/~/running-crew
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

domain:
  name: http://localhost:8080