spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/running-crew
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true


cloud:
  aws:
    credentials:
      access-key: ${s3.accesskey}
      secret-key: ${s3.secretkey}
    region:
      static: ${s3.resion}
    s3:
      bucket: ${s3.bucket}
    stack:
      auto: false


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



fcm:
  key:
    path: fcm/running-crew-project-firebase-adminsdk-ta9q7-fa58725efe.json