spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/running-crew
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true




cloud:
  aws:
    credentials:
      accessKey: AKIAQP4HH4EEFLZRD27U # test-user-yongsoo IAM 사용자의 엑세스 키
      secretKey: +LSBk21aAoI6Ki8wIJ1mP+qeXPzZq0R17xdrIWup # test-user-yongsoo IAM 사용자의 비밀 키
    s3:
      bucket: running-crew-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false




logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



fcm:
  key:
    path: fcm/running-crew-project-firebase-adminsdk-ta9q7-fa58725efe.json