spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/running-crew
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true


cloud:
  aws:
    credentials:
      access-key: AKIAQP4HH4EEITRO3TZY
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: s3-running-crew
    stack:
      auto: false


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



fcm:
  key:
    path: fcm/running-crew-project-firebase-adminsdk-ta9q7-fa58725efe.json