spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/running-crew
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true




cloud:
  aws:
    credentials:
      accessKey: AKIAQP4HH4EELRPC7VWE
      secretKey: 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
    s3:
      bucket: s3-running-crew
    region:
      static: ap-northeast-2
    stack:
      auto: false




logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



fcm:
  key:
    path: fcm/running-crew-project-firebase-adminsdk-ta9q7-fa58725efe.json